apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
        - name: estoque
          image: produtos-estoque:1.0.0
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: estoque-service
spec:
  selector:
    app: estoque
  ports:
    - port: 3000
      targetPort: 3000